import { PortfolioItem } from '@/types/portfolio';

export const portfolioItems: PortfolioItem[] = [
  // Images
  {
    id: '1',
    title: 'Lifestyle Outdoor Portrait',
    category: 'lifestyle',
    type: 'image',
    src: '/images/portfolio-lifestyle-outdoor.JPG',
    description: 'Outdoor lifestyle photography session',
  },
  {
    id: '2',
    title: 'Glamour Portrait',
    category: 'fashion',
    type: 'image',
    src: '/images/portfolio-glamour-portrait.JPG',
    description: 'Professional glamour portrait',
  },
  {
    id: '3',
    title: 'Client Consultation',
    category: 'commercial',
    type: 'image',
    src: '/images/about-client-consultation.jpg',
    description: 'Professional client consultation session',
  },
  {
    id: '4',
    title: 'Behind the Scenes',
    category: 'lifestyle',
    type: 'image',
    src: '/images/about-behind-the-scenes-1.jpg',
    description: 'Behind the scenes photography',
  },
  {
    id: '5',
    title: 'Creative Session',
    category: 'lifestyle',
    type: 'image',
    src: '/images/about-behind-the-scenes-2.jpg',
    description: 'Creative photography session',
  },
  {
    id: '6',
    title: 'Photographer at Work',
    category: 'commercial',
    type: 'image',
    src: '/images/hero-homepage-photographer-client.jpg',
    description: 'Professional photographer with client',
  },
  {
    id: '7',
    title: 'Client Experience',
    category: 'lifestyle',
    type: 'image',
    src: '/images/services-client-experience.jpg',
    description: 'Client reviewing their photos',
  },
  {
    id: '8',
    title: 'Videography Equipment',
    category: 'commercial',
    type: 'image',
    src: '/images/hero-videography-equipment.jpg',
    description: 'Professional videography setup',
  },
  // Videos
  {
    id: '9',
    title: 'Medical Aesthetics',
    category: 'commercial',
    type: 'video',
    src: '/videos/hero-medical-aesthetics.MP4',
    description: 'Medical aesthetics promotional video',
  },
  {
    id: '10',
    title: 'Plato Coffee Commercial',
    category: 'commercial',
    type: 'video',
    src: '/videos/portfolio-commercial-plato-coffee.MOV',
    description: 'Café promotional video',
  },
  {
    id: '11',
    title: 'Medical Reskin Full',
    category: 'commercial',
    type: 'video',
    src: '/videos/portfolio-medical-reskin-full.MOV',
    description: 'Reskin Medical Aesthetics full video',
  },
  {
    id: '12',
    title: 'Lifestyle Fashion Pink',
    category: 'lifestyle',
    type: 'video',
    src: '/videos/portfolio-lifestyle-fashion-pink.MOV',
    description: 'Lifestyle fashion video',
  },
  {
    id: '13',
    title: 'Fashion Blue Dress',
    category: 'fashion',
    type: 'video',
    src: '/videos/portfolio-fashion-blue-dress.MOV',
    description: 'Fashion video with blue dress',
  },
  {
    id: '14',
    title: 'Lifestyle Café',
    category: 'lifestyle',
    type: 'video',
    src: '/videos/portfolio-lifestyle-cafe-red.MP4',
    description: 'Lifestyle video at café',
  },
];
